[package]
distribution = "2201.12.0"
org = "ballerinax"
name = "alfresco"
version = "@toml.version@"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["Content Management", "Document Management", "ECM", "DMS", "Vendor/Alfresco", "Area/Documents", "Type/Connector"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-alfresco"

[build-options]
observabilityIncluded = true

[platform.java21]
graalvmCompatible = true
